<?php
declare(strict_types=1);
namespace Ecl\Auth;

use Cake\Auth\AbstractPasswordHasher;

/**
 * Class StrongPasswordHasher
 *
 * @package Ecl\Auth
 */
class StrongPasswordHasher extends AbstractPasswordHasher
{
    /**
     * Generates password hash.
     *
     * @param  string $password Plain text password to hash.
     * @return bool|string Password hash or false on failure
     * @link https://book.cakephp.org/3.0/en/controllers/components/authentication.html#hashing-passwords
     */
    public function hash($password)
    {
        return Password::hash($password);
    }

    /**
     * Check hash. Generate hash for user provided password and check against existing hash.
     *
     * @param  string $password Plain text password to hash.
     * @param  string $hashedPassword Existing hashed password.
     * @return bool True if hashes match else false.
     */
    public function check($password, $hashedPassword)
    {
        return password_verify($password, $hashedPassword);
    }

    /**
     * Returns true if the password need to be rehashed, due to the password being
     * created with anything else than the passwords generated by this class.
     *
     * @param  string $password The password to verify
     * @return bool
     * @noinspection PhpMissingParentCallCommonInspection
     */
    public function needsRehash($password): bool
    {
        return !(bool)preg_match('/^\$6\$[a-z0-9]+\$\w+/', $password);
    }
}
